from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from uuid import UUID

    from mlcopilot.domain.api_key import ApiKey
    from mlcopilot.domain.oauth_account import OAuthAccount
    from mlcopilot.domain.password_reset_token import PasswordResetToken
    from mlcopilot.domain.refresh_token import RefreshToken
    from mlcopilot.domain.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...


class RefreshTokenRepository(Protocol):
    async def get_by_id(self, token_id: UUID) -> RefreshToken | None: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def list_active_by_family(self, family_id: UUID) -> list[RefreshToken]: ...
    async def add(self, token: RefreshToken) -> None: ...
    async def update(self, token: RefreshToken) -> None: ...
    async def revoke_family(self, family_id: UUID) -> None: ...


class ApiKeyRepository(Protocol):
    async def get_by_id(self, key_id: UUID) -> ApiKey | None: ...
    async def get_by_hash(self, key_hash: str) -> ApiKey | None: ...
    async def list_active_for_user(self, user_id: UUID) -> list[ApiKey]: ...
    async def add(self, api_key: ApiKey) -> None: ...
    async def update(self, api_key: ApiKey) -> None: ...


class OAuthAccountRepository(Protocol):
    async def get_by_provider_and_id(
        self, provider: str, provider_account_id: str,
    ) -> OAuthAccount | None: ...
    async def get_by_user_id(self, user_id: UUID) -> list[OAuthAccount]: ...
    async def add(self, account: OAuthAccount) -> None: ...
    async def delete_by_user_and_provider(self, user_id: UUID, provider: str) -> None: ...


class PasswordResetTokenRepository(Protocol):
    async def get_by_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def add(self, token: PasswordResetToken) -> None: ...
    async def mark_used(self, token_id: UUID) -> None: ...
