"""Domain entities and protocol definitions for Chat & RAG."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from collections.abc import AsyncIterator


@dataclass(frozen=True)
class Citation:
    """Snapshot citation reference linked to a specific text chunk."""

    upload_id: uuid.UUID
    filename: str
    chunk_id: uuid.UUID
    content: str
    position: int
    score: float


@dataclass(frozen=True)
class ChatMessage:
    """Turn-based record of a user or assistant response inside a conversation."""

    id: uuid.UUID
    conversation_id: uuid.UUID
    role: str  # 'user' or 'assistant'
    content: str
    citations: list[Citation]
    created_at: datetime


@dataclass
class Conversation:
    """Aggregate root grouping chat history sessions and messages."""

    id: uuid.UUID
    project_id: uuid.UUID
    title: str
    created_by: uuid.UUID
    created_at: datetime
    messages: list[ChatMessage] = field(default_factory=list)


@dataclass(frozen=True)
class RetrievedChunk:
    """Intermediate data container for text chunk information loaded during RAG retrieval."""

    chunk_id: uuid.UUID
    upload_id: uuid.UUID
    filename: str
    content: str
    position: int
    score: float


@dataclass(frozen=True)
class ChatResponse:
    """Final output generated by the RAG orchestrator service."""

    content: str
    citations: list[Citation]


class LLMProvider(Protocol):
    """Abstract protocol for communicating with Large Language Models (LLMs)."""

    async def generate(self, system_prompt: str, user_prompt: str) -> str:
        """Execute a blocking complete text generation call."""
        ...

    def generate_stream(
        self, system_prompt: str, user_prompt: str
    ) -> AsyncIterator[str]:
        """Execute a streaming text generation call returning token chunks."""
        ...


class ConversationRepository(Protocol):
    """Persistence repository protocol for Conversation and ChatMessage aggregates."""

    async def get_by_id(self, conversation_id: uuid.UUID) -> Conversation | None:
        """Retrieve a conversation and its messages by ID."""
        ...

    async def list_by_project(
        self, project_id: uuid.UUID, user_id: uuid.UUID
    ) -> list[Conversation]:
        """List all conversations belonging to a project and user."""
        ...

    async def add(self, conversation: Conversation) -> None:
        """Persist a new conversation session record."""
        ...

    async def delete(self, conversation_id: uuid.UUID) -> None:
        """Delete a conversation session and all its messages."""
        ...

    async def add_message(self, message: ChatMessage) -> None:
        """Persist a single chat message turn."""
        ...

    async def get_messages(self, conversation_id: uuid.UUID) -> list[ChatMessage]:
        """Fetch all messages for a conversation ordered by time."""
        ...

    async def commit(self) -> None:
        """Commit the active database transaction."""
        ...
